//QUERRIES FOR THE DB//

'PRINTING DONE'

UPDATE PrintingData SET Printed = True
WHERE Printed = False;

'PROGRAM STATE'

UPDATE Active SET Active.CurrentlyActive = True;

'BEFORE EXPORT MERGE TABLE INTO A TEMPORARY ONE'

INSERT INTO PrintingData ( SZEM_ADOAZON, SZEM_TAJSZAM, SZEM_ELONEV, SZEM_CSNEV, SZEM_UNEV,
 SZEM_UNEV2, SZEM_SZCSNEV, SZEM_SZULNEV, SZEM_SZULNEV2, SZEM_SZULHELY, SZEM_SZULDATUM,
 SZEM_ACSNEV, SZEM_AUNEV, SZEM_AUNEV2, SZEM_NEME, SZEMV_ALLAMPOLG, SZEMV_KFILL, SZEMV_KFOKSZAM,
 SZEMV_KFALLAM, SZEMV_KFBIZT, SZEMV_KFBIZTORSZ, SZEMV_KFBIZTKEZD, SZEMV_KFBIZTVEGE, SZEMV_OSTERMIG,
 SZEMV_CSNYILVAN, CIM_CIMTIP, CIM_ORSZKOD, CIM_TELNEV, CIM_TEL_AZON, CIM_KSH, CIM_IRSZAM, CIM_KHELYSEG,
 CIM_KOZNEV, CIM_KOZJEL, CIM_HAZSZAM, CIM_EPULET, CIM_LEPCSOHAZ, CIM_EMELET, CIM_AJTO, FV_TORZSSZAM, FG_FOGSOR,
 FV_SZERVEGYSEG, FV_FKSZLA, FV_TEMASZAM, FV_COFOG, FV_JOGTIPKOD, FG_JOGVKEZDETE, FV_BERTABLA, FG_MLTIP, FG_ELSOJOGV,
 FG_ISKVEGE, FV_MUNKAREND, FV_MIDOBEOSZT, FV_FMUSZAKREND, FV_FMIDOJEL, FV_FG_JIDOTARTAM, FV_FSTATUSZ, FV_MTIP, FV_FG_TOHOSZ,
 FV_TEHOSZ, FV_FG_HAVIORA, FG_PROBAIDOKEZD, FG_PROBAIDOVEG, FG_BESKEZD, FG_VKSZKEZD, FG_JUBSZKEZD, FG_SZNYSZKEZD, FG_SZJSZKEZD,
 FV_MKOR, FV_FKOR, FV_BESKULCSSZAM, FV_BESFEOR, FV_BESBERTABLA, FV_FG_KULCSSZAM, FV_FEOR, FV_FG_BERTABLA, FV_KOVKOTLEP, FV_UTMOD,
 FV_AZON, FV_FG_NEV, FV_KJAZON, FV_KJNEV, FV_MJAZON, FV_MJNEV, FV_ERKEP, FV_FOGTER, FV_UGYESZSEGIMEGB, FV_ESKU, FV_JELMINTA, FV_JELKEZD,
 FV_INDITAS, HMREFERATURA, EFOKFTEV, FOGLINF, KOZALKIDO, ASZISZKEZD, FV_HATVEGE, FV_HATJELLEG, FV_FG_HATFEL, FV_HADOAZON, FV_HFOGSOR,
 FV_HATOK, FSZLA_FSZLA, FSZLA_FIXOSSZEG, FSZLA_PRIORITAS, FSZLA_NSZAZALEK, FSZLA_ALAPERT, FLT_ILLTIP, FLT_JOGCIM, FLT_NEV,
 FLT_RSZAZALEK, FLT_RERTEKE, FLT_SZAZALEK, FLT_ERTEKE, FLT_KEZDETE, FLT_VEGE, ISK_KVJELZO, ISK_KVKOD, ISK_KVEGYEB, ISK_EDAT,
 ISK_EJOGSZAB, ISK_EJOGKOV, ISK_INTEZMENY, ISK_SZAK, ISK_MDAT, ISK_OKLEVEL, ISK_KVBEJEL, Egyedi_SzerV_AZON )
SELECT Szemely.SZEM_ADOAZON, Szemely.SZEM_TAJSZAM, Szemely.SZEM_ELONEV, Szemely.SZEM_CSNEV, Szemely.SZEM_UNEV, Szemely.SZEM_UNEV2,
 Szemely.SZEM_SZCSNEV, Szemely.SZEM_SZULNEV, Szemely.SZEM_SZULNEV2, Szemely.SZEM_SZULHELY, Szemely.SZEM_SZULDATUM, Szemely.SZEM_ACSNEV,
 Szemely.SZEM_AUNEV, Szemely.SZEM_AUNEV2, Szemely.SZEM_NEME, Szemely.SZEMV_ALLAMPOLG, Szemely.SZEMV_KFILL, Szemely.SZEMV_KFOKSZAM, Szemely.SZEMV_KFALLAM,
 Szemely.SZEMV_KFBIZT, Szemely.SZEMV_KFBIZTORSZ, Szemely.SZEMV_KFBIZTKEZD, Szemely.SZEMV_KFBIZTVEGE, Szemely.SZEMV_OSTERMIG,
 Szemely.SZEMV_CSNYILVAN, Address.CIM_CIMTIP, Address.CIM_ORSZKOD, Address.CIM_TELNEV, Address.CIM_TEL_AZON, 
 Address.CIM_KSH, Address.CIM_IRSZAM, Address.CIM_KHELYSEG, Address.CIM_KOZNEV, Address.CIM_KOZJEL, Address.CIM_HAZSZAM, 
 Address.CIM_EPULET, Address.CIM_LEPCSOHAZ, Address.CIM_EMELET, Address.CIM_AJTO, Foglalkoztatas.FV_TORZSSZAM,
 Foglalkoztatas.FG_FOGSOR, Foglalkoztatas.FV_SZERVEGYSEG, Foglalkoztatas.FV_FKSZLA, Foglalkoztatas.FV_TEMASZAM,
 Foglalkoztatas.FV_COFOG, Foglalkoztatas.FV_JOGTIPKOD, Foglalkoztatas.FG_JOGVKEZDETE, Foglalkoztatas.FV_BERTABLA, 
 Foglalkoztatas.FG_MLTIP, Foglalkoztatas.FG_ELSOJOGV, Foglalkoztatas.FG_ISKVEGE, Foglalkoztatas.FV_MUNKAREND,
 Foglalkoztatas.FV_MIDOBEOSZT, Foglalkoztatas.FV_FMUSZAKREND, Foglalkoztatas.FV_FMIDOJEL, Foglalkoztatas.FV_FG_JIDOTARTAM, 
 Foglalkoztatas.FV_FSTATUSZ, Foglalkoztatas.FV_MTIP, Foglalkoztatas.FV_FG_TOHOSZ, Foglalkoztatas.FV_TEHOSZ, Foglalkoztatas.FV_FG_HAVIORA, 
 Foglalkoztatas.FG_PROBAIDOKEZD, Foglalkoztatas.FG_PROBAIDOVEG, Foglalkoztatas.FG_BESKEZD, Foglalkoztatas.FG_VKSZKEZD,
 Foglalkoztatas.FG_JUBSZKEZD, Foglalkoztatas.FG_SZNYSZKEZD, Foglalkoztatas.FG_SZJSZKEZD, Foglalkoztatas.FV_MKOR, Foglalkoztatas.FV_FKOR,
 Foglalkoztatas.FV_BESKULCSSZAM, Foglalkoztatas.FV_BESFEOR, Foglalkoztatas.FV_BESBERTABLA, Foglalkoztatas.FV_FG_KULCSSZAM,
 Foglalkoztatas.FV_FEOR, Foglalkoztatas.FV_FG_BERTABLA, Foglalkoztatas.FV_KOVKOTLEP, Foglalkoztatas.FV_UTMOD, Foglalkoztatas.FV_AZON, 
 Foglalkoztatas.FV_FG_NEV, Foglalkoztatas.FV_KJAZON, Foglalkoztatas.FV_KJNEV, Foglalkoztatas.FV_MJAZON, Foglalkoztatas.FV_MJNEV,
 Foglalkoztatas.FV_ERKEP, Foglalkoztatas.FV_FOGTER, Foglalkoztatas.FV_UGYESZSEGIMEGB, Foglalkoztatas.FV_ESKU, Foglalkoztatas.FV_JELMINTA,
 Foglalkoztatas.FV_JELKEZD, Foglalkoztatas.FV_INDITAS, Foglalkoztatas.HMREFERATURA, Foglalkoztatas.EFOKFTEV, Foglalkoztatas.FOGLINF,
 Foglalkoztatas.KOZALKIDO, Foglalkoztatas.ASZISZKEZD, HATFOG.FV_HATVEGE, HATFOG.FV_HATJELLEG, HATFOG.FV_FG_HATFEL, HATFOG.FV_HADOAZON,
 HATFOG.FV_HFOGSOR, HATFOG.FV_HATOK, SZAMLA.FSZLA_FSZLA, SZAMLA.FSZLA_FIXOSSZEG, SZAMLA.FSZLA_PRIORITAS, SZAMLA.FSZLA_NSZAZALEK, SZAMLA.FSZLA_ALAPERT,
 Illetmeny.FLT_ILLTIP, Illetmeny.FLT_JOGCIM, Illetmeny.FLT_NEV, Illetmeny.FLT_RSZAZALEK, Illetmeny.FLT_RERTEKE, Illetmeny.FLT_SZAZALEK,
 Illetmeny.FLT_ERTEKE, Illetmeny.FLT_KEZDETE, Illetmeny.FLT_VEGE, Vegzettseg.ISK_KVJELZO, Vegzettseg.ISK_KVKOD, Vegzettseg.ISK_KVEGYEB,
 Vegzettseg.ISK_EDAT, Vegzettseg.ISK_EJOGSZAB, Vegzettseg.ISK_EJOGKOV, Vegzettseg.ISK_INTEZMENY, Vegzettseg.ISK_SZAK, Vegzettseg.ISK_MDAT,
 Vegzettseg.ISK_OKLEVEL, Vegzettseg.ISK_KVBEJEL, Foglalkoztatas.Egyedi_SzerV_AZON
FROM (((((Szemely LEFT JOIN Address ON Szemely.SZEM_ADOAZON = Address.AD_AZON_CIM) LEFT JOIN Foglalkoztatas ON
 Szemely.SZEM_ADOAZON = Foglalkoztatas.Fog_AD_AZON) LEFT JOIN HATFOG ON Szemely.SZEM_ADOAZON = HATFOG.ADO_HATFOG)
 LEFT JOIN Illetmeny ON Szemely.SZEM_ADOAZON = Illetmeny.Ill_AD_AZON) LEFT JOIN SZAMLA ON Szemely.SZEM_ADOAZON = SZAMLA.SZAMLA_AD_AZON)
 LEFT JOIN Vegzettseg ON Szemely.SZEM_ADOAZON = Vegzettseg.Kep_AD_AZON
WHERE (((Szemely.SZEM_ADOAZON)=Tempvars!printAdo) And ((Vegzettseg.Valid)=DateValue("31/12/3999")) And
 ((Address.AD_AZON_CIM)=Szemely.SZEM_ADOAZON) And ((Address.Valid)=DateValue("31/12/3999")) And 
 ((Foglalkoztatas.Fog_AD_AZON)=Szemely.SZEM_ADOAZON) And ((Foglalkoztatas.Valid)=DateValue("31/12/3999")) And
 ((Illetmeny.Ill_AD_AZON)=Szemely.SZEM_ADOAZON) And ((Illetmeny.Valid)=DateValue("31/12/3999")) And ((Vegzettseg.Kep_AD_AZON)=Szemely.SZEM_ADOAZON));




'EXPORT DONE SELECTED DATA MARKS THIS AS WELL'

UPDATE ((((((Szemely INNER JOIN exportálni ON Szemely.SZEM_ADOAZON = exportálni.SZEM_ADOAZON)
INNER JOIN Address ON Szemely.SZEM_ADOAZON = Address.AD_AZON_CIM) INNER JOIN Foglalkoztatas ON
 Szemely.SZEM_ADOAZON = Foglalkoztatas.Fog_AD_AZON) INNER JOIN HATFOG ON
 Szemely.SZEM_ADOAZON = HATFOG.ADO_HATFOG) INNER JOIN Illetmeny ON
 Szemely.SZEM_ADOAZON = Illetmeny.Ill_AD_AZON) INNER JOIN SZAMLA ON
 Szemely.SZEM_ADOAZON = SZAMLA.SZAMLA_AD_AZON) INNER JOIN Vegzettseg ON
 Szemely.SZEM_ADOAZON = Vegzettseg.Kep_AD_AZON SET Szemely.Export = True,
 SZAMLA.Exported = True, Address.Export = True, Foglalkoztatas.Exported = True,
 HATFOG.Exported = True, Illetmeny.Exported = True, Vegzettseg.Exported = Yes
WHERE (((Szemely.SZEM_ADOAZON)=[exportálni].[SZEM_ADOAZON]));

